AllCops:
  TargetRubyVersion: 2.4

Gemspec/RequiredRubyVersion:
  Severity: warning

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 100
  Severity: warning

Metrics/AbcSize:
  Max: 16

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'test/unit/**/*'
    - 'Rakefile'

Metrics/ClassLength:
  Severity: warning

Metrics/MethodLength:
  Max: 13
  Severity: warning

Style/Documentation:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 3

Style/NegatedIf:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
