language: ruby
cache: bundler

services:
  - docker

before_install:
  # Install Bundler v2 as Travis still uses v1.x
  - gem update --system
  - gem install bundler
  # Pull images to avoid extraneous output when calling `terraform` wrapper
  - for v in $TERRAFORM_VERSIONS; do docker pull hashicorp/terraform:$v; done

script: bundle exec rake "test[$TERRAFORM_VERSIONS]"

rvm:
  - 3.0.0
  - 2.7.2
  - 2.6.6
  - 2.5.8
  - 2.4.10

env:
  global:
    - TERRAFORM_VERSIONS="0.14.5 0.13.6 0.12.30 0.11.14"
